community_name: "Global Sports"
community_tagline: "Full game video, your highlight reels and more"
community_description:  "The best place on the web for athletes and fans"
support_email:  "admin@globalsports.net"
meta_description: 'A description of your community for use in META tags.'
meta_keywords: "football, baseball, quarterback, fun, lazy, friendly, soccer, wild"
sections_enabled: ['photos', 'posts', 'clippings', 'contests', 'categories', 'events']
show_advertising: true
closed_beta_mode: false

# The label you use for 'staff' writers (featured writer, staff, pro, etc.)
featured_writer_label: 'Featured Athletes'

photo:
  missing_thumb: '/plugin_assets/community_engine/images/icon_missing_thumb.gif'
  missing_medium: "/plugin_assets/community_engine/images/icon_missing_medium.gif"
  attachment_fu_options:
    resize_to: "465>"
    min_size: 1    
    #size in megabytes
    max_size: 5
    thumbnails: {icon: "60x40", feature: "103x65", thumb: "100x100", profile: "215x175", medium: "290x320>", large: "664>"}
    #options - 's3', 'file_system', 'db_system' - see attachment_fu for details
    storage: 'file_system'
    content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']

feature:
  use_thumbs: true
  dimensions: [150, 635]
  attachment_fu_options:
    resize_to: "465>"
    min_size: 1    
    max_size: 1
    thumbnails: {thumb: '45x45!', large: '635x150!'}    
    storage: 'file_system'
    content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']
    
video_asset:
  missing_thumb: '/plugin_assets/community_engine/images/icon_missing_thumb.gif'
  missing_medium: "/plugin_assets/community_engine/images/icon_missing_medium.gif"
  attachment_fu_options:
    #resize_to: "465>"
    min_size: 1    
    #size in megabytes
    max_size: 2500
    #thumbnails: {thumb: "100x100!", medium: "290x320!", large: "664>"}
    #options - 's3', 'file_system', 'db_system' - see attachment_fu for details
    storage: 'file_system'
    #content_type: "#{Vidavee.legal_file_extensions}"
        
clipping:
  attachment_fu_options:
    resize_to: "465>"
    min_size: 1    
    max_size: 3
    thumbnails: {thumb: "100x100!", medium_square: "200x200!", medium: "200>"}
    storage: 'file_system'
    content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']

theme: gsbasic